name = "digitalitzacio-4eso"
main = "src/worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[assets]
directory = "./public"

# Després de crear la base de dades D1 des del tauler de Cloudflare,
# substitueix REPLACE_WITH_D1_DATABASE_ID pel seu ID real.
[[d1_databases]]
binding = "DB"
database_name = "digitalitzacio-4eso"
database_id = "390d2f66-91a9-49d8-a5ae-7629d0ee74de"
migrations_dir = "migrations"

[ai]
binding = "AI"
